import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/budget.dart';
import '../models/transaction.dart';

class PdfService {
  static Future<Uint8List> buildPdf(PdfPageFormat format, Budget budget, String currencySymbol) async {
    final pdf = pw.Document();
    
    try {
      pw.Font fontRegular;
      pw.Font fontBold;
      String displayCurrency;

      try {
        // Try to load custom fonts from Google Fonts
        fontRegular = await PdfGoogleFonts.interRegular();
        fontBold = await PdfGoogleFonts.interBold();
        displayCurrency = currencySymbol; 
      } catch (e) {
        // Fallback to standard fonts if loading fails (e.g. offline)
        print('Error loading fonts: $e');
        fontRegular = pw.Font.helvetica();
        fontBold = pw.Font.helveticaBold();
        displayCurrency = '${budget.currency} '; 
      }

      pdf.addPage(
        pw.Page(
          pageFormat: format,
          theme: pw.ThemeData.withFont(
            base: fontRegular,
            bold: fontBold,
          ),
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Header
                pw.Header(
                  level: 0,
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text('Budget Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800)),
                      pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.end,
                        children: [
                          pw.Text(DateFormat('MMM d, y').format(DateTime.now()), style: const pw.TextStyle(color: PdfColors.grey700)),
                          pw.Text('Generated by Budget Tracker', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
                        ],
                      ),
                    ],
                  ),
                ),
                pw.SizedBox(height: 30),

                // Summary
                pw.Container(
                  padding: const pw.EdgeInsets.all(15),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.grey100,
                    borderRadius: pw.BorderRadius.circular(10),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('${budget.name}', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey900)),
                      pw.Divider(thickness: 1, color: PdfColors.grey400),
                      pw.SizedBox(height: 10),
                      pw.Row(
                        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                        children: [
                           _buildSummaryItem('Initial Budget', '$displayCurrency${budget.budget.toStringAsFixed(2)}'),
                           _buildSummaryItem('Current Balance', '$displayCurrency${budget.balance.toStringAsFixed(2)}', isBold: true),
                        ]
                      ),
                      pw.SizedBox(height: 10),
                      pw.Row(
                        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                        children: [
                           _buildSummaryItem('Total Income', '$displayCurrency${budget.totalIncome.toStringAsFixed(2)}', color: PdfColors.green700),
                           _buildSummaryItem('Total Expenses', '$displayCurrency${budget.totalExpenses.toStringAsFixed(2)}', color: PdfColors.red700),
                        ]
                      ),
                    ],
                  ),
                ),
                pw.SizedBox(height: 30),

                // Transactions Table
                pw.Text('Transaction History', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800)),
                pw.SizedBox(height: 10),
                pw.Table.fromTextArray(
                  context: context,
                  headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                  headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey600),
                  rowDecoration: const pw.BoxDecoration(color: PdfColors.grey50),
                  border: null,
                  cellPadding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 10),
                  data: _buildTableData(budget, displayCurrency),
                ),
              ],
            );
          },
        ),
      );
    } catch (e, stackTrace) {
      // If ANY error occurs, calculate it and show it in the PDF
      pdf.addPage(
        pw.Page(
          pageFormat: format,
          build: (pw.Context context) {
            return pw.Center(
               child: pw.Text("Error generating PDF: $e\n\n$stackTrace", style: const pw.TextStyle(color: PdfColors.red, fontSize: 12)),
            );
          },
        ),
      );
    }

    return pdf.save();
  }

  static List<List<String>> _buildTableData(Budget budget, String currencySymbol) {
    // Sort transactions by date (Oldest first for statement view)
    final transactions = List<Transaction>.from(budget.transactions);
    transactions.sort((a, b) => a.date.compareTo(b.date));

    List<List<String>> data = [
      ['Date', 'Title', 'Type', 'Amount', 'Balance'], 
    ];

    double runningBalance = budget.budget; 

    for (var t in transactions) {
      if (t.isExpense) {
        runningBalance -= t.amount;
      } else {
        runningBalance += t.amount;
      }

      data.add([
        DateFormat('MMM d, y').format(t.date),
        t.title,
        t.isExpense ? 'Expense' : 'Income',
        '$currencySymbol${t.amount.toStringAsFixed(2)}',
        '$currencySymbol${runningBalance.toStringAsFixed(2)}',
      ]);
    }
    
    return data;
  }

  static pw.Widget _buildSummaryItem(String label, String value, {bool isBold = false, PdfColor? color}) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label, style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600)),
        pw.Text(value, style: pw.TextStyle(fontSize: 14, fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal, color: color ?? PdfColors.black)),
      ],
    );
  }
}
